$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$lake = (& elan which lake).Trim()
if (-not (Test-Path -LiteralPath $lake)) { throw 'Unable to locate the active Lake executable.' }
$temporaryFile = Join-Path ([System.IO.Path]::GetTempPath()) 'DriftingIdentifiabilityPromotedAxiomAudit.lean'

$declarations = @(
  'DriftingIdentifiability.gaussianKernelNormalizer_injective',
  'DriftingIdentifiability.gaussianKernelNormalizer_proportional_constant_eq_one',
  'DriftingIdentifiability.hasFDerivAt_log_gaussianKernelNormalizer',
  'DriftingIdentifiability.gaussianMeanShift_eq_imp_kernelNormalizer_eq',
  'DriftingIdentifiability.gaussianMeanShiftDrift_identifiesAtZero',
  'DriftingIdentifiability.multivariateGaussian_exponentialTiltCentroid',
  'DriftingIdentifiability.multivariateGaussian_laplaceMeanShiftDrift_radial_tendsto',
  'DriftingIdentifiability.gaussianRadialLimit_zero_imp_parameters_eq',
  'DriftingIdentifiability.laplaceGaussianMeanShiftDrift_identifiesAtZero',
  'DriftingIdentifiability.bothMultivariateGaussian_allowsDistinctPair',
  'DriftingIdentifiability.laplaceGaussianCandidate_identifiesAtZero',
  'DriftingIdentifiability.laplaceGaussianCandidate_isLegitimate',
  'DriftingIdentifiability.hasFDerivAt_laplaceCompanionNormalizer',
  'DriftingIdentifiability.hasFDerivAt_laplaceCompanionNormalizer_meanShift',
  'DriftingIdentifiability.integral_laplaceWeightedDisplacement_eq',
  'DriftingIdentifiability.laplace_meanShiftRegularAt',
  'DriftingIdentifiability.laplaceZeroDrift_iff_crossDisplacement',
  'DriftingIdentifiability.laplaceZeroDrift_tiltCentroid_eq',
  'DriftingIdentifiability.laplaceKernel_smul_id_integrable''',
  'DriftingIdentifiability.laplaceKernelNormalizer_injective',
  'DriftingIdentifiability.laplaceSmoothingInjective_real',
  'DriftingIdentifiability.laplaceMomentParts_eq_of_zeroDrift_dirac_real',
  'DriftingIdentifiability.laplaceZeroDrift_dirac_identifies_real',
  'DriftingIdentifiability.laplaceCompanionNormalizer_pos',
  'DriftingIdentifiability.hasDerivAt_laplaceCompanionNormalizer',
  'DriftingIdentifiability.hasDerivAt_laplaceDisplacementIntegral',
  'DriftingIdentifiability.laplaceZeroDrift_imp_eq_of_companionAligned',
  'DriftingIdentifiability.laplaceZeroDrift_atomic_weights_eq',
  'DriftingIdentifiability.laplaceZeroDrift_atomic_identifies',
  'DriftingIdentifiability.laplaceCrossDisplacementScalar_decomposition_exp',
  'DriftingIdentifiability.laplaceZeroDrift_decomposition_exp',
  'DriftingIdentifiability.hasDerivWithinAt_lowerCompensatedMoment',
  'DriftingIdentifiability.lowerCompensatedMoment_proportional',
  'DriftingIdentifiability.laplaceZeroDrift_identifies_of_truncatedPairing_eq_zero',
  'DriftingIdentifiability.laplaceZeroDrift_identifies_of_rightDense_zeroMassGaps',
  'DriftingIdentifiability.hasDerivWithinAt_Ici_laplaceKernelNormalizer',
  'DriftingIdentifiability.hasDerivWithinAt_Ici_crossDisplacement_of_kernelNormalizerRightDeriv',
  'DriftingIdentifiability.hasDerivWithinAt_Ici_laplaceCrossDisplacement',
  'DriftingIdentifiability.laplaceBalance_identity_of_hasDerivWithinAt_Ici_crossDisplacement',
  'DriftingIdentifiability.laplaceBalance_identity_of_kernelNormalizerRightDeriv',
  'DriftingIdentifiability.laplaceBalance_identity_of_zeroDrift',
  'DriftingIdentifiability.zeroDrift_middlePairing_eq_neg_two_scaledLower',
  'DriftingIdentifiability.zeroDrift_truncatedPairing_eq_zero_iff_upperPairing',
  'DriftingIdentifiability.zeroDrift_truncatedPairing_eq_zero_iff_middlePairing',
  'DriftingIdentifiability.laplaceZeroDrift_identifies_of_upperPairing_eq_zero',
  'DriftingIdentifiability.laplaceZeroDrift_identifies_of_middlePairing_eq_zero',
  'DriftingIdentifiability.continuous_laplaceKernelNormalizer',
  'DriftingIdentifiability.lowerExpMass_tendsto_atTop_integral',
  'DriftingIdentifiability.upperExpMass_tendsto_atBot_integral',
  'DriftingIdentifiability.laplaceKernelNormalizerWronskian_eq_massDet',
  'DriftingIdentifiability.laplaceKernelNormalizer_wronskian_zero_imp_eq',
  'DriftingIdentifiability.laplaceKernelNormalizer_wronskian_eq_zero_imp_eq',
  'DriftingIdentifiability.laplaceKernelNormalizerWronskian_eq_of_sum_gap_zero',
  'DriftingIdentifiability.laplaceKernelNormalizerWronskian_eq_zero_on_gap_of_p_connection',
  'DriftingIdentifiability.laplaceKernelNormalizerWronskian_eq_zero_on_gap_of_p_twoSided',
  'DriftingIdentifiability.laplaceKernelNormalizerWronskian_eq_zero_of_right_tail',
  'DriftingIdentifiability.laplaceKernelNormalizerWronskian_eq_zero_of_left_tail',
  'DriftingIdentifiability.laplaceKernelNormalizerWronskian_continuousWithinAt_Ici',
  'DriftingIdentifiability.laplaceKernelNormalizerWronskian_tendsto_atTop_zero',
  'DriftingIdentifiability.laplaceKernelNormalizerWronskian_tendsto_atBot_zero',
  'DriftingIdentifiability.laplaceMeanShiftRatio_common_self',
  'DriftingIdentifiability.laplaceMeanShiftRatio_common_of_zeroDrift',
  'DriftingIdentifiability.laplaceCommonODE_companion_value_of_firstOrder',
  'DriftingIdentifiability.laplaceCommonODE_value_of_companion_derivative',
  'DriftingIdentifiability.hasDerivAt_wronskian_of_laplace_commonODE',
  'DriftingIdentifiability.hasDerivAt_laplaceKernelNormalizerWronskian_of_commonMeanShift',
  'DriftingIdentifiability.hasDerivAt_laplaceKernelNormalizerWronskian_of_zeroDrift',
  'DriftingIdentifiability.ae_hasDerivAt_laplaceKernelNormalizerWronskian_of_zeroDrift',
  'DriftingIdentifiability.abel_zero_propagates_Icc',
  'DriftingIdentifiability.abel_integratingFactor_const_Icc',
  'DriftingIdentifiability.eventually_const_eq_zero_of_tendsto_zero',
  'DriftingIdentifiability.abel_right_tail_zero_of_integratingFactor_const',
  'DriftingIdentifiability.abel_left_tail_zero_of_integratingFactor_const',
  'DriftingIdentifiability.abel_right_tail_zero_of_integratingFactor',
  'DriftingIdentifiability.abel_left_tail_zero_of_integratingFactor',
  'DriftingIdentifiability.bounded_factor_const_zero_of_factor_tendsto_zero',
  'DriftingIdentifiability.bounded_integratingFactor_const_zero_of_factor_tendsto_zero',
  'DriftingIdentifiability.hasDerivAt_laplaceCompanionWronskian',
  'DriftingIdentifiability.laplaceZeroDrift_imp_eq_of_companionWronskian_const',
  'DriftingIdentifiability.PaperFiniteIdentifiability.finiteBasisDensitiesEqual',
  'DriftingIdentifiability.PaperFiniteIdentifiability.finitePopulationMeanShift_identifies',
  'DriftingIdentifiability.PaperFiniteIdentifiability.finitePopulationMeanShift_identifies_of_probeZero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.finitePopulationMeanShift_identifies_of_probeEnergy_eq_zero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.finitePopulationMeanShift_identifies_of_energy',
  'DriftingIdentifiability.PaperFiniteIdentifiability.PopulationMeanShiftFiniteSetup.coefficientStability',
  'DriftingIdentifiability.PaperFiniteIdentifiability.PopulationMeanShiftFiniteSetup.coefficientStability_probeEnergy',
  'DriftingIdentifiability.PaperFiniteIdentifiability.interactionFrameBound_of_linearIndependent',
  'DriftingIdentifiability.PaperFiniteIdentifiability.interactionFrameBound_inverseCertificate',
  'DriftingIdentifiability.PaperFiniteIdentifiability.interactionFrameBound_of_uniformPerturbation',
  'DriftingIdentifiability.PaperFiniteIdentifiability.interactionFrameBound_of_strictPairScaling',
  'DriftingIdentifiability.PaperFiniteIdentifiability.interactionFrameBound_of_dualCertificate',
  'DriftingIdentifiability.PaperFiniteIdentifiability.interactionFrameBound_le_interactionNorm',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPoint_frameConstant_le',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPointFrameConstant_le',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPoint_identifies_of_probeZero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPoint_identifies_of_probeEnergy_eq_zero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.empirical01Gaussian_identifies_of_probeZero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.bumpDensity_contDiff',
  'DriftingIdentifiability.PaperFiniteIdentifiability.bumpBasisMeasure_noAtoms',
  'DriftingIdentifiability.PaperFiniteIdentifiability.bumpInteractionFrameBound',
  'DriftingIdentifiability.PaperFiniteIdentifiability.bumpGaussian_identifies_of_probeEnergy_eq_zero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.PopulationMeanShiftFiniteSetup.coefficientStability_of_estimate',
  'DriftingIdentifiability.PaperFiniteIdentifiability.PopulationMeanShiftFiniteSetup.estimate_failure_measure_le',
  'DriftingIdentifiability.PaperFiniteIdentifiability.meas_gt_le_meanSquare_div',
  'DriftingIdentifiability.PaperFiniteIdentifiability.PopulationMeanShiftFiniteSetup.estimate_failure_le_meanSquare',
  'DriftingIdentifiability.PaperFiniteIdentifiability.sampleMean_concentration',
  'DriftingIdentifiability.SelfNormalized.selfNormalized_meanSquare_le',
  'DriftingIdentifiability.Algorithm2.algorithm2Affinity_nonneg',
  'DriftingIdentifiability.Algorithm2.algorithm2Affinity_le_one',
  'DriftingIdentifiability.Algorithm2.algorithm2PositiveWeight_le',
  'DriftingIdentifiability.Algorithm2.algorithm2NegativeWeight_le',
  'DriftingIdentifiability.Algorithm2.algorithm2Drift_eq_affinityPairSum',
  'DriftingIdentifiability.Algorithm2.algorithm2Drift_eq_massScaledCentroid',
  'DriftingIdentifiability.Algorithm2.algorithm2PositiveMass_pos',
  'DriftingIdentifiability.Algorithm2.algorithm2NegativeMass_pos',
  'DriftingIdentifiability.Algorithm2.algorithm2Drift_eq_massProduct_centroidDiff',
  'DriftingIdentifiability.Algorithm2.algorithm2Drift_norm_le',
  'DriftingIdentifiability.Algorithm2.algorithm2Drift_norm_le_affinityMass',
  'DriftingIdentifiability.Algorithm2.algorithm2Drift_matched_zero',
  'DriftingIdentifiability.Algorithm2.algorithm2ColumnReweightedWeight_pos',
  'DriftingIdentifiability.Algorithm2.algorithm2Affinity_false_eq_rowScale_mul_columnReweightedWeight',
  'DriftingIdentifiability.Algorithm2.algorithm2PositiveCentroid_false_eq_columnReweighted',
  'DriftingIdentifiability.Algorithm2.algorithm2NegativeCentroid_false_eq_columnReweighted',
  'DriftingIdentifiability.Algorithm2.algorithm2Drift_false_eq_zero_iff_centroidDiff_eq_zero',
  'DriftingIdentifiability.Algorithm2.centroidDiff_norm_le_inv_massProduct_mul_drift_norm',
  'DriftingIdentifiability.Algorithm2.algorithm2PositiveCentroid_false_meanSquare_le',
  'DriftingIdentifiability.Algorithm2.algorithm2NegativeCentroid_false_meanSquare_le',
  'DriftingIdentifiability.Algorithm2.meanSquare_sub_sub_le_two_add',
  'DriftingIdentifiability.Algorithm2.columnReweightedKernel_pos',
  'DriftingIdentifiability.Algorithm2.algorithm2Drift_false_eq_zero_iff_noMaskCentroidDrift_eq_zero',
  'DriftingIdentifiability.Algorithm2.maskedWeight_eq_factor_mul_noMaskWeight',
  'DriftingIdentifiability.Algorithm2.div_sqrt_mass_perturbation',
  'DriftingIdentifiability.Algorithm2.deletedDrift_false_eq_algorithm2Drift',
  'DriftingIdentifiability.Algorithm2.eyeMask_column_unmasked',
  'DriftingIdentifiability.Algorithm2.maskedMassProduct_sub_deletedMassProduct_le',
  'DriftingIdentifiability.Algorithm2.algorithm2Affinity_sub_deletedAffinity_abs_le',
  'DriftingIdentifiability.Algorithm2.algorithm2Drift_sub_deletedDrift_norm_le_of_affinity',
  'DriftingIdentifiability.Algorithm2.algorithm2Drift_sub_deletedDrift_norm_le',
  'DriftingIdentifiability.Algorithm2.algorithm2Drift_sub_deletedDrift_norm_le_eyeMask',
  'DriftingIdentifiability.SelfNormalized.selfNormalizedIndexed_meanSquare_le',
  'DriftingIdentifiability.SelfNormalized.weightSum_lower_tail_prob_le',
  'DriftingIdentifiability.SelfNormalized.selfNormalizedIndexed_deviation_prob_le',
  'DriftingIdentifiability.PaperFiniteIdentifiability.interactionFrameBound_of_probeScaling',
  'DriftingIdentifiability.PaperFiniteIdentifiability.interactionFrameBound_of_biScaling',
  'DriftingIdentifiability.PaperFiniteIdentifiability.interactionFrameBound_of_positiveGain',
  'DriftingIdentifiability.PaperFiniteIdentifiability.inducedInteractionVector_sinkhornOrbit01_eq',
  'DriftingIdentifiability.PaperFiniteIdentifiability.sinkhornOrbit01_identifies_of_probeEnergy_eq_zero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.sinkhornOrbit01_coefficientStability',
  'DriftingIdentifiability.PaperFiniteIdentifiability.oneStepBalanced01_identifies_of_probeEnergy_eq_zero',
  'DriftingIdentifiability.SelfNormalized.weightSum_deviation_prob_le',
  'DriftingIdentifiability.SelfNormalized.selfNormalizedCentroid_relative_perturbation',
  'DriftingIdentifiability.SelfNormalized.abs_inv_sqrt_sub_inv_sqrt_le',
  'DriftingIdentifiability.SelfNormalized.abs_sum_sub_sum_le_of_rel',
  'DriftingIdentifiability.SelfNormalized.abs_mul_sub_mul_le_of_rel',
  'DriftingIdentifiability.Algorithm2.twoStepWeight_rel_of_rowMass_rel',
  'DriftingIdentifiability.Algorithm2.twoStepBalancedMatrixAffinity_eq_commonScale_mul_weight',
  'DriftingIdentifiability.Algorithm2.twoStepBalancedMatrixCentroid_eq_weightCentroid',
  'DriftingIdentifiability.Algorithm2.twoStepLevelMass_rel_of_rowMass_rel',
  'DriftingIdentifiability.Algorithm2.secondBalancedColumnProfile_rel_of_rowMass_rel',
  'DriftingIdentifiability.Algorithm2.threeStepWeight_rel_of_rowMass_rel',
  'DriftingIdentifiability.Algorithm2.balancedThreeStepNormalizedDrift_deviation_prob_le_of_centroids',
  'DriftingIdentifiability.Algorithm2.balancedThreeStepCentroid_deviation_prob_le_of_mass_tails',
  'DriftingIdentifiability.Algorithm2.balancedTwoStepNormalizedDrift_deviation_prob_le_of_centroids',
  'DriftingIdentifiability.Algorithm2.balancedTwoStepCentroid_deviation_prob_le',
  'DriftingIdentifiability.Algorithm2.balancedTwoStepCentroid_eq_matrixCentroid',
  'DriftingIdentifiability.Algorithm2.deletedDrift_eq_massProduct_centroidDiff',
  'DriftingIdentifiability.Algorithm2.deletedAffinity_eq_rowScale_mul_deletedColumnWeight',
  'DriftingIdentifiability.Algorithm2.deletedColumnWeight_inl_eq',
  'DriftingIdentifiability.Algorithm2.deletedPositiveCentroid_eq_columnReweighted',
  'DriftingIdentifiability.Algorithm2.deletedNegativeCentroid_eq_deletedColumnWeight',
  'DriftingIdentifiability.Algorithm2.deletedPositiveCentroid_eq_algorithm2PositiveCentroid_false',
  'DriftingIdentifiability.Algorithm2.deletedPositiveCentroid_meanSquare_le',
  'DriftingIdentifiability.Algorithm2.deletedNegativeCentroid_meanSquare_le',
  'DriftingIdentifiability.FeatureModel.law_eq_of_feature_identifiesAtZero',
  'DriftingIdentifiability.FeatureModel.source_eq_of_law_eq',
  'DriftingIdentifiability.FeatureModel.source_eq_of_feature_identifiesAtZero',
  'DriftingIdentifiability.allFeatureLawsEqual_of_each_feature_identifiesAtZero',
  'DriftingIdentifiability.source_eq_of_allFeatureLawsEqual_of_embedding',
  'DriftingIdentifiability.source_eq_of_each_feature_identifiesAtZero_of_embedding',
  'DriftingIdentifiability.featureLaw_dirac_eq_of_collision',
  'DriftingIdentifiability.featureLaw_collision_distinct_source_diracs',
  'DriftingIdentifiability.HeterogeneousFeatureFamily.source_eq_of_allLawsEqual_of_embedding',
  'DriftingIdentifiability.HeterogeneousFeatureFamily.measureDetermining_of_embedding',
  'DriftingIdentifiability.HeterogeneousFeatureFamily.allLawsEqual_of_each_feature_identifiesAtZero',
  'DriftingIdentifiability.HeterogeneousFeatureFamily.source_eq_of_each_feature_identifiesAtZero_of_measureDetermining',
  'DriftingIdentifiability.HeterogeneousFeatureFamily.source_eq_of_each_feature_identifiesAtZero_of_embedding',
  'DriftingIdentifiability.HeterogeneousFeatureFamily.sourceDist_le_of_featureDist_le',
  'DriftingIdentifiability.HeterogeneousFeatureFamily.sourceDist_le_zero_of_featureDist_zero',
  'DriftingIdentifiability.HeterogeneousFeatureFamily.source_eq_of_featureDist_zero_of_stability',
  'DriftingIdentifiability.PaperFiniteIdentifiability.affineParallelCoefficientsAreEqual',
  'DriftingIdentifiability.PaperFiniteIdentifiability.affineCoefficientMinorsVanish',
  'DriftingIdentifiability.PaperFiniteIdentifiability.affineCoefficientIdentifiable',
  'DriftingIdentifiability.PaperFiniteIdentifiability.affineBasisDensitiesEqual',
  'DriftingIdentifiability.PaperFiniteIdentifiability.affineCoeff_l1_le_minor_mass',
  'DriftingIdentifiability.PaperFiniteIdentifiability.affineCoeffL1_le_of_frame_scaledDrift',
  'DriftingIdentifiability.PaperFiniteIdentifiability.cfgGenerated_eq_target_of_effective_eq',
  'DriftingIdentifiability.PaperFiniteIdentifiability.cfgEffective_eq_conditional_of_generated_eq_target',
  'DriftingIdentifiability.PaperFiniteIdentifiability.basisDensity_cfgNegativeCoefficients',
  'DriftingIdentifiability.PaperFiniteIdentifiability.basisDensity_cfgTargetCoefficients',
  'DriftingIdentifiability.PaperFiniteIdentifiability.cfgWeightedNegativeCoefficients_eq_cfgNegativeCoefficients',
  'DriftingIdentifiability.PaperFiniteIdentifiability.basisDensity_cfgWeightedNegativeCoefficients',
  'DriftingIdentifiability.PaperFiniteIdentifiability.AffineDriftFiniteSetup.identifiesCoefficients',
  'DriftingIdentifiability.PaperFiniteIdentifiability.AffineDriftFiniteSetup.identifiesDensities',
  'DriftingIdentifiability.PaperFiniteIdentifiability.CFGDriftFiniteSetup.effectiveNegative_eq_conditional',
  'DriftingIdentifiability.PaperFiniteIdentifiability.CFGDriftFiniteSetup.generated_eq_cfgTarget',
  'DriftingIdentifiability.PaperFiniteIdentifiability.CFGDriftFiniteSetup.generatedDensity_eq_cfgTargetDensity',
  'DriftingIdentifiability.PaperFiniteIdentifiability.ColumnReweightedMeanShiftFiniteSetup.identifies_of_probeZero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.ColumnReweightedMeanShiftFiniteSetup.identifies_of_probeEnergy_eq_zero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.ColumnReweightedMeanShiftFiniteSetup.coefficientStability',
  'DriftingIdentifiability.PaperFiniteIdentifiability.ColumnReweightedMeanShiftFiniteSetup.coefficientStability_of_estimate',
  'DriftingIdentifiability.PaperFiniteIdentifiability.ColumnReweightedMeanShiftFiniteSetup.estimate_failure_le_meanSquare',
  'DriftingIdentifiability.PaperFiniteIdentifiability.algorithm2Kernel_eq_laplaceKernel',
  'DriftingIdentifiability.PaperFiniteIdentifiability.inducedInteractionVector_columnReweighted01_eq_smul',
  'DriftingIdentifiability.PaperFiniteIdentifiability.columnReweighted01_interactionNorm_eq',
  'DriftingIdentifiability.PaperFiniteIdentifiability.columnReweighted01_interactionNorm_ge',
  'DriftingIdentifiability.PaperFiniteIdentifiability.columnReweighted01_frameBound_of_bare',
  'DriftingIdentifiability.PaperFiniteIdentifiability.columnReweighted01_identifies_of_probeEnergy_eq_zero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.columnReweighted01_coefficientStability',
  'DriftingIdentifiability.PaperFiniteIdentifiability.columnReweighted01_estimate_failure_le_meanSquare',
  'DriftingIdentifiability.PaperFiniteIdentifiability.linearIndependent_weightedGeometricProfiles',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPoint_basisNondegenerate',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPointFrameBound',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPointCertifiedFrameBound',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPoint_identifies',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPoint_coefficientStability',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPoint_coefficientStability_one',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPoint_coefficientStability_probeEnergy',
  'DriftingIdentifiability.PaperFiniteIdentifiability.empiricalInteractionFrameBound',
  'DriftingIdentifiability.PaperFiniteIdentifiability.empirical01Gaussian_identifies',
  'DriftingIdentifiability.PaperFiniteIdentifiability.empirical01Gaussian_identifies_of_probeEnergy_eq_zero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.empirical01Gaussian_coefficientStability',
  'DriftingIdentifiability.PaperFiniteIdentifiability.empirical01Gaussian_coefficientStability_probeEnergy',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPointND_identifies_of_probeEnergy_eq_zero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPointND_coefficientStability_probeEnergy',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPointCertifiedProbe_identifies_of_probeEnergy_eq_zero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.gaussianEmpiricalPointCertifiedProbe_coefficientStability_probeEnergy',
  'DriftingIdentifiability.PaperFiniteIdentifiability.continuousPerturbation_identifies_of_probeEnergy_eq_zero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.empirical01Laplace_identifies_of_probeEnergy_eq_zero',
  'DriftingIdentifiability.PaperFiniteIdentifiability.empirical01Laplace_coefficientStability_probeEnergy',
  'DriftingIdentifiability.CandidateConditions.finitePopulationMeanShiftCandidate_identifiesAtZero',
  'DriftingIdentifiability.CandidateConditions.finitePopulationMeanShiftCandidate_isLegitimate',
  'DriftingIdentifiability.aggregateTemperatureDrift_cancels',
  'DriftingIdentifiability.aggregateTemperatureDrift_zero_with_nonzero_component'
)

$allowedProjectAxioms = @(
  'antisymmetric_kernel_induces_basis_antisymmetry',
  'equation_11_bilinear_mean_shift',
  'equation_31_bilinear_expansion',
  'sampleMean_meanSquare_le'
)

$sourceLines = [System.Collections.Generic.List[string]]::new()
$sourceLines.Add('import DriftingIdentifiability')
$sourceLines.Add('import DriftingIdentifiability.Extensions')
foreach ($declaration in $declarations) {
  $sourceLines.Add("#print axioms $declaration")
}

$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText(
  $temporaryFile,
  ($sourceLines -join [Environment]::NewLine) + [Environment]::NewLine,
  $utf8WithoutBom
)

Push-Location $root
try {
  $output = (& $lake env lean $temporaryFile 2>&1 | Out-String)
  if ($LASTEXITCODE -ne 0) {
    Write-Error $output
    exit $LASTEXITCODE
  }
} finally {
  Pop-Location
  Remove-Item -LiteralPath $temporaryFile -Force -ErrorAction SilentlyContinue
}

$found = [regex]::Matches(
  $output,
  'DriftingIdentifiability\.Paper\.([A-Za-z_][A-Za-z0-9_]*)'
) | ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique

$unexpected = @($found | Where-Object { $_ -notin $allowedProjectAxioms })
if ($unexpected.Count -gt 0) {
  Write-Error (
    'Promoted theorem dependency audit found forbidden project axioms: ' +
    ($unexpected -join ', ')
  )
  exit 1
}

Write-Host (
  "Promoted theorem axiom audit passed: $($declarations.Count) declarations; " +
  'no conditional Gaussian/RKHS dependencies.'
)
