"""Frozen machinery for the corrected K=200 F1 confirmation.

This module intentionally leaves the exploratory ``f1.py`` / ``run_f1.py``
artifact family untouched.  The confirmation uses new seeds, globally disjoint
allocations, one shared kernel, checkpoint-matched vetoes, and source-hash
compatibility checks.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch

from . import cifar
from .appearance import precision_recall
from .config import MASTER_SEED, GeometryConfig, derive_seed
from .diagnostics import PACKAGE, ROOT
from .f1 import (
    BANK,
    CALIBRATION_SAMPLES,
    CONTROL_RECALL_FLOOR,
    ETA,
    EVAL_REFERENCE,
    PARTICLES,
    POSITIVES,
    RECALL_GATE,
    TARGET_ESS,
    _interval,
    duplicate_rate,
    effective_rank,
    frozen_update,
    nn_diversity,
    score,
)
from .fixed_features import build_family
from .kernels import calibrate_block_kernel
from .models import OneStepGenerator, sample_latent


HERE = Path(__file__).resolve().parent
PROTOCOL = ROOT / "numerics" / "EncoderIndependentF1K200ConfirmationProtocol.md"

CONFIRMATION_SEED_OFFSET = 61000
UNIT_IDS = (100, 101, 102)
REGIMES = ("replay", "stochastic")
ARMS = ("real_data", "random_generator")
CHECKPOINTS = (0, 10, 20, 40, 100, 200)
GRID_CHECKPOINTS = (0, 40, 200)
REFERENCE_CHUNK = 256


def frozen_config() -> dict:
    """The behavior-changing configuration recorded in the freeze artifact."""
    return {
        "protocol": str(PROTOCOL.relative_to(ROOT)).replace("\\", "/"),
        "seed_offset": CONFIRMATION_SEED_OFFSET,
        "unit_ids": list(UNIT_IDS),
        "regimes": list(REGIMES),
        "arms": list(ARMS),
        "checkpoints": list(CHECKPOINTS),
        "resolution": 32,
        "particles": PARTICLES,
        "positives": POSITIVES,
        "bank": BANK,
        "calibration_samples": CALIBRATION_SAMPLES,
        "eval_reference": EVAL_REFERENCE,
        "eta": ETA,
        "target_ess_fraction": TARGET_ESS,
        "recall_gate": RECALL_GATE,
        "control_recall_floor": CONTROL_RECALL_FLOOR,
        "geometry": "raw",
        "base_kernel": "smooth_laplace",
        "direction_mode": "paper",
        "normalization": "rms",
        "denominator_floor": 1e-30,
        "self_mask": False,
        "correction": "R11 scalar",
    }


def source_manifest() -> dict[str, str]:
    """Hash every executable source covered by ``diagnostics.provenance``."""
    sources = sorted(PACKAGE.glob("*.py")) + sorted(
        (PACKAGE / "tests").glob("*.py"))
    return {
        str(path.relative_to(ROOT)).replace("\\", "/"):
            hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sources
    }


def protocol_sha256() -> str:
    return hashlib.sha256(PROTOCOL.read_bytes()).hexdigest()


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verify_sidecar(path: Path) -> None:
    sidecar = path.with_suffix(path.suffix + ".sha256")
    if not path.exists() or not sidecar.exists():
        raise RuntimeError(f"artifact or SHA sidecar missing: {path}")
    recorded = sidecar.read_text(encoding="utf-8").split()[0]
    actual = file_sha256(path)
    if recorded != actual:
        raise RuntimeError(
            f"SHA mismatch for {path.name}: recorded {recorded}, actual {actual}")


def load_freeze(path: Path) -> dict:
    verify_sidecar(path)
    freeze = json.loads(path.read_text(encoding="utf-8"))
    if freeze.get("source_sha256") != source_manifest():
        raise RuntimeError("current Python sources do not match the F1 freeze")
    if freeze.get("protocol_sha256") != protocol_sha256():
        raise RuntimeError("the K=200 protocol changed after the F1 freeze")
    if freeze.get("config") != frozen_config():
        raise RuntimeError("the executable K=200 configuration changed after freeze")
    return freeze


def load_compatible_artifact(path: Path, freeze: dict) -> dict:
    """Load an artifact only if its bytes and source provenance are frozen."""
    verify_sidecar(path)
    payload = json.loads(path.read_text(encoding="utf-8"))
    recorded = payload.get("provenance", {}).get("source_sha256")
    if recorded != freeze["source_sha256"]:
        raise RuntimeError(
            f"{path.name} was generated by sources different from the freeze")
    return payload


def confirmation_seed(unit: int | str, role: str) -> int:
    return derive_seed(MASTER_SEED + CONFIRMATION_SEED_OFFSET,
                       "f1-k200", unit, role)


@dataclass(frozen=True)
class ConfirmationAllocation:
    calibration: np.ndarray
    banks: dict[int, np.ndarray]
    controls: dict[int, np.ndarray]
    stochastic_pool: np.ndarray
    pool_size: int

    def assert_disjoint(self) -> None:
        named: dict[str, np.ndarray] = {"calibration": self.calibration}
        named |= {f"bank_{u}": self.banks[u] for u in UNIT_IDS}
        named |= {f"control_{u}": self.controls[u] for u in UNIT_IDS}
        for name, values in named.items():
            if len(values) != len(np.unique(values)):
                raise AssertionError(f"{name} contains duplicate indices")
        keys = sorted(named)
        for index, left in enumerate(keys):
            for right in keys[index + 1:]:
                overlap = np.intersect1d(named[left], named[right])
                if overlap.size:
                    raise AssertionError(
                        f"{left} and {right} overlap by {overlap.size} indices")
        protected = np.concatenate(
            [self.calibration] + [self.controls[u] for u in UNIT_IDS])
        if np.intersect1d(protected, self.stochastic_pool).size:
            raise AssertionError("stochastic pool contains protected indices")

    @property
    def digests(self) -> dict:
        values = {"calibration": self.calibration,
                  "stochastic_pool": self.stochastic_pool}
        values |= {f"bank_{u}": self.banks[u] for u in UNIT_IDS}
        values |= {f"control_{u}": self.controls[u] for u in UNIT_IDS}
        return {
            name: hashlib.sha256(np.asarray(indices).tobytes()).hexdigest()[:16]
            for name, indices in values.items()
        }


def confirmation_allocation(resolution: int, root: str | None
                            ) -> ConfirmationAllocation:
    """Allocate all confirmation roles from one permutation, globally disjoint."""
    pool_size = len(cifar.cifar_pool(resolution, "train", root))
    order = np.random.default_rng(
        confirmation_seed("global", "allocation")).permutation(pool_size)
    cursor = 0
    calibration = np.sort(order[cursor:cursor + CALIBRATION_SAMPLES])
    cursor += CALIBRATION_SAMPLES
    banks: dict[int, np.ndarray] = {}
    controls: dict[int, np.ndarray] = {}
    for unit in UNIT_IDS:
        banks[unit] = np.sort(order[cursor:cursor + BANK])
        cursor += BANK
        controls[unit] = np.sort(order[cursor:cursor + PARTICLES])
        cursor += PARTICLES
    if cursor > pool_size:
        raise ValueError("training pool is too small for the confirmation")
    protected = np.concatenate(
        [calibration] + [controls[u] for u in UNIT_IDS])
    stochastic_pool = np.setdiff1d(np.arange(pool_size), protected)
    allocation = ConfirmationAllocation(
        calibration=calibration, banks=banks, controls=controls,
        stochastic_pool=stochastic_pool, pool_size=pool_size)
    allocation.assert_disjoint()
    return allocation


def build_shared_kernel(allocation: ConfirmationAllocation, resolution: int,
                        root: str | None, device):
    """Calibrate once on the globally shared target-only subset."""
    branch = build_family(
        GeometryConfig(family="raw", base_kernel="smooth_laplace",
                       target_ess_fraction=TARGET_ESS), 3).branches[0]
    pool = cifar.cifar_pool(resolution, "train", root)
    samples = pool[torch.as_tensor(allocation.calibration)].to(device)
    kernel = calibrate_block_kernel(
        branch, samples, "smooth_laplace", 0.5, 1.0, 1e-3, combine="sum",
        target_ess_fraction=TARGET_ESS)
    return branch, kernel


def confirmation_source(arm: str, unit: int, allocation: ConfirmationAllocation,
                        resolution: int, root: str | None, device) -> torch.Tensor:
    pool = cifar.cifar_pool(resolution, "train", root)
    if arm == "real_data":
        return pool[torch.as_tensor(allocation.controls[unit])].to(device)
    if arm == "random_generator":
        model = OneStepGenerator(
            32, 3, resolution, 64,
            confirmation_seed(unit, "source-init")).to(device)
        latent = sample_latent(
            PARTICLES, 32, confirmation_seed(unit, "source-latent"), device)
        with torch.no_grad():
            return model(latent).detach()
    raise ValueError(f"unknown confirmation arm {arm!r}")


def confirmation_replay_schedule(unit: int, steps: int) -> np.ndarray:
    rng = np.random.default_rng(confirmation_seed(unit, "replay-schedule"))
    return np.stack([rng.choice(BANK, size=POSITIVES, replace=False)
                     for _ in range(steps)])


def confirmation_rollout(
        start: torch.Tensor, unit: int, regime: str,
        allocation: ConfirmationAllocation, branch, kernel,
        resolution: int, root: str | None, device,
        on_checkpoint=None) -> dict:
    """K=200 paired rollout using explicit shared allocation and kernel."""
    train = cifar.cifar_pool(resolution, "train", root)
    steps = max(CHECKPOINTS)
    state = start.clone().to(device)
    if regime == "replay":
        bank = train[torch.as_tensor(allocation.banks[unit])]
        schedule = confirmation_replay_schedule(unit, steps)
        stream = None
    elif regime == "stochastic":
        bank = None
        schedule = None
        stream = np.random.default_rng(
            confirmation_seed(unit, "stochastic-stream"))
    else:
        raise ValueError(f"unknown regime {regime!r}")

    def positives_at(step: int) -> torch.Tensor:
        if regime == "replay":
            indices = schedule[step]
            return bank[torch.as_tensor(indices)].to(device)
        positions = stream.integers(
            0, len(allocation.stochastic_pool), size=POSITIVES)
        indices = allocation.stochastic_pool[positions]
        return train[torch.as_tensor(indices)].to(device)

    # A separate deterministic pre-evaluation must not consume the stochastic
    # rollout stream.
    if regime == "replay":
        pre_positive = bank[torch.as_tensor(schedule[0])].to(device)
    else:
        pre_rng = np.random.default_rng(
            confirmation_seed(unit, "stochastic-pre-evaluation"))
        positions = pre_rng.integers(
            0, len(allocation.stochastic_pool), size=POSITIVES)
        pre_positive = train[torch.as_tensor(
            allocation.stochastic_pool[positions])].to(device)
    with torch.no_grad():
        _, pre = frozen_update(state, pre_positive, branch, kernel)

    history, pending = [], [pre]
    for step in range(steps + 1):
        if step in CHECKPOINTS:
            entry = {"step": step, **_interval(pending)}
            if on_checkpoint is not None:
                entry |= on_checkpoint(state, step)
            history.append(entry)
            pending = []
        if step == steps:
            break
        with torch.no_grad():
            state, record = frozen_update(
                state, positives_at(step), branch, kernel)
        pending.append(record)
    return {
        "final": state,
        "history": history,
        "schedule_digest": None if schedule is None else hashlib.sha256(
            schedule.astype(np.int32).tobytes()).hexdigest()[:16],
    }


def nearest_reference_distances(
        images: torch.Tensor, reference: torch.Tensor, device,
        chunk: int = REFERENCE_CHUNK) -> tuple[torch.Tensor, torch.Tensor]:
    """Exact pixel-space nearest reference distances, chunked for a 6GB GPU."""
    queries = images.detach().to(device).reshape(len(images), -1).float()
    qnorm = (queries * queries).sum(dim=1, keepdim=True)
    best = torch.full((len(queries),), float("inf"), device=device)
    claimed = torch.full((len(queries),), -1, dtype=torch.long, device=device)
    for start in range(0, len(reference), chunk):
        block = reference[start:start + chunk].to(device).reshape(
            -1, queries.shape[1]).float()
        bnorm = (block * block).sum(dim=1).unsqueeze(0)
        squared = (qnorm + bnorm - 2.0 * queries @ block.T).clamp_min_(0.0)
        values, positions = squared.min(dim=1)
        improve = values < best
        best[improve] = values[improve]
        claimed[improve] = positions[improve] + start
    return best.sqrt().cpu(), claimed.cpu()


def stochastic_memorization_statistics(
        images: torch.Tensor, reference: torch.Tensor, normalizer: float,
        device) -> dict:
    distances, claimed = nearest_reference_distances(
        images, reference, device)
    return {
        "nearest_train_normalized": float(distances.median()) / normalizer,
        "nearest_train_distribution": distances.numpy().tolist(),
        "distinct_train_claimed": int(torch.unique(claimed).numel()),
        "claimed_train_indices": claimed.numpy().tolist(),
    }


def reference_side_interval(recall: float, trials: int = EVAL_REFERENCE,
                            confidence: float = 0.95) -> dict:
    """Exact binomial diagnostic over covered reference indicators only."""
    from scipy.stats import beta
    covered = int(round(float(recall) * trials))
    alpha = 1.0 - confidence
    low = 0.0 if covered == 0 else float(
        beta.ppf(alpha / 2, covered, trials - covered + 1))
    high = 1.0 if covered == trials else float(
        beta.ppf(1 - alpha / 2, covered + 1, trials - covered))
    return {
        "covered": covered,
        "trials": trials,
        "confidence": confidence,
        "interval": [low, high],
        "scope": "reference-side diagnostic only; not total recall uncertainty",
    }


def evaluate_veto(regime: str, terminal: dict, memorization: dict,
                  replay_thresholds: dict,
                  stochastic_threshold: float) -> dict:
    """Apply every applicable calibrated threshold, with no placeholder path."""
    comparisons = {
        "effective_rank": {
            "value": float(terminal["effective_rank"]),
            "threshold": float(replay_thresholds["effective_rank"]),
        },
        "one_minus_duplicate_rate": {
            "value": 1.0 - float(terminal["duplicate_rate"]),
            "threshold": float(replay_thresholds["one_minus_duplicate_rate"]),
        },
        "nn_diversity": {
            "value": float(terminal["nn_diversity"]),
            "threshold": float(replay_thresholds["nn_diversity"]),
        },
    }
    if regime == "replay":
        comparisons |= {
            "nearest_bank_normalized": {
                "value": float(memorization["nearest_bank_normalized"]),
                "threshold": float(
                    replay_thresholds["nearest_bank_normalized"]),
            },
            "distinct_bank": {
                "value": float(memorization["distinct_bank"]),
                "threshold": float(replay_thresholds["distinct_bank"]),
            },
        }
    elif regime == "stochastic":
        comparisons["nearest_train_normalized"] = {
            "value": float(memorization["nearest_train_normalized"]),
            "threshold": float(stochastic_threshold),
        }
    else:
        raise ValueError(f"unknown regime {regime!r}")
    for item in comparisons.values():
        item["passes"] = bool(item["value"] >= item["threshold"])
    return {
        "comparisons": comparisons,
        "passes": bool(all(item["passes"] for item in comparisons.values())),
    }


def decide(rows: list[dict]) -> dict:
    """Paired per-regime conjunction and strict positive-control semantics."""
    by_key = {(row["unit"], row["arm"], row["regime"]): row for row in rows}
    per_regime = {}
    for regime in REGIMES:
        units = {}
        for unit in UNIT_IDS:
            control = by_key[(unit, "real_data", regime)]
            primary = by_key[(unit, "random_generator", regime)]
            control_valid = bool(
                control["terminal"]["recall"] > CONTROL_RECALL_FLOOR)
            recall_passes = bool(primary["terminal"]["recall"] > RECALL_GATE)
            veto_passes = bool(primary["veto"]["passes"])
            units[str(unit)] = {
                "control_recall": control["terminal"]["recall"],
                "control_valid": control_valid,
                "primary_recall": primary["terminal"]["recall"],
                "recall_passes": recall_passes,
                "veto_passes": veto_passes,
                "replicate_pass": bool(
                    control_valid and recall_passes and veto_passes),
            }
        failed_controls = [unit for unit, item in units.items()
                           if not item["control_valid"]]
        passes = sum(item["replicate_pass"] for item in units.values())
        if len(failed_controls) >= 2:
            decision = "VOID"
        else:
            decision = "PASS" if passes >= 2 else "FAIL"
        per_regime[regime] = {
            "decision": decision,
            "units_passing": int(passes),
            "units_failing_control": failed_controls,
            "units": units,
        }
    return {
        "recall_gate": RECALL_GATE,
        "control_recall_floor": CONTROL_RECALL_FLOOR,
        "per_regime": per_regime,
        "reading": ", ".join(
            f"{regime}={per_regime[regime]['decision']} "
            f"({per_regime[regime]['units_passing']}/3 pass)"
            for regime in REGIMES),
    }


def lightweight_score(images: torch.Tensor, reference_features: np.ndarray,
                      real: torch.Tensor, device) -> dict:
    """Use the existing frozen score without the invalid particle bootstrap."""
    result = score(images, reference_features, real, device, resamples=0)
    result["reference_side_interval"] = reference_side_interval(result["recall"])
    return result
